[package]
name = "hardware-common"
description = "Common utilities and types for hardware related crates"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
num-format = { workspace = true }