use super::{PartitionTypeInfo, PartitionTypeInfoFlags};

pub const PARTITION_TYPES: [PartitionTypeInfo; 13] = [
    PartitionTypeInfo::new(
        "apm",
        "apple",
        "Apple_Unix_SVR2",
        "Apple UFS",
        PartitionTypeInfoFlags::None,
        "",
    ),
    PartitionTypeInfo::new(
        "apm",
        "apple",
        "Apple_HFS",
        "Apple HFS/HFS",
        PartitionTypeInfoFlags::None,
        "",
    ),
    PartitionTypeInfo::new(
        "apm",
        "apple",
        "Apple_partition_map",
        "Apple Partition Map",
        PartitionTypeInfoFlags::None,
        "",
    ),
    PartitionTypeInfo::new(
        "apm",
        "apple",
        "Apple_Free",
        "Unused",
        PartitionTypeInfoFlags::None,
        "",
    ),
    PartitionTypeInfo::new(
        "apm",
        "apple",
        "Apple_Scratch",
        "Empty",
        PartitionTypeInfoFlags::None,
        "",
    ),
    PartitionTypeInfo::new(
        "apm",
        "apple",
        "Apple_Driver",
        "Driver",
        PartitionTypeInfoFlags::None,
        "",
    ),
    PartitionTypeInfo::new(
        "apm",
        "apple",
        "Apple_Driver43",
        "Driver 4.3",
        PartitionTypeInfoFlags::None,
        "",
    ),
    PartitionTypeInfo::new(
        "apm",
        "apple",
        "Apple_PRODOS",
        "ProDOS file system",
        PartitionTypeInfoFlags::None,
        "",
    ),
    PartitionTypeInfo::new(
        "apm",
        "microsoft",
        "DOS_FAT_12",
        "FAT 12",
        PartitionTypeInfoFlags::None,
        "",
    ),
    PartitionTypeInfo::new(
        "apm",
        "microsoft",
        "DOS_FAT_16",
        "FAT 16",
        PartitionTypeInfoFlags::None,
        "",
    ),
    PartitionTypeInfo::new(
        "apm",
        "microsoft",
        "DOS_FAT_32",
        "FAT 32",
        PartitionTypeInfoFlags::None,
        "",
    ),
    PartitionTypeInfo::new(
        "apm",
        "microsoft",
        "Windows_FAT_16",
        "FAT 16 (Windows)",
        PartitionTypeInfoFlags::None,
        "",
    ),
    PartitionTypeInfo::new(
        "apm",
        "microsoft",
        "Windows_FAT_32",
        "FAT 32 (Windows)",
        PartitionTypeInfoFlags::None,
        "",
    ),
];
