use super::{PartitionTypeInfo, PartitionTypeInfoFlags};

pub static COMMON_DOS_TYPES: [PartitionTypeInfo; 6] = [
    // Linux filesystem - ext4
    PartitionTypeInfo::new(
        "dos",
        "linux",
        "0x83",
        "Linux (ext4)",
        PartitionTypeInfoFlags::None,
        "ext4",
    ),
    // Linux filesystem - ext3
    PartitionTypeInfo::new(
        "dos",
        "linux",
        "0x83",
        "Linux (ext3)",
        PartitionTypeInfoFlags::None,
        "ext3",
    ),
    // Linux swap
    PartitionTypeInfo::new(
        "dos",
        "linux",
        "0x82",
        "Linux Swap",
        PartitionTypeInfoFlags::Swap,
        "swap",
    ),
    // FAT32 (LBA)
    PartitionTypeInfo::new(
        "dos",
        "microsoft",
        "0x0c",
        "FAT32 (LBA)",
        PartitionTypeInfoFlags::None,
        "vfat",
    ),
    // NTFS/exFAT/HPFS - NTFS
    PartitionTypeInfo::new(
        "dos",
        "microsoft",
        "0x07",
        "NTFS",
        PartitionTypeInfoFlags::None,
        "ntfs",
    ),
    // NTFS/exFAT/HPFS - exFAT
    PartitionTypeInfo::new(
        "dos",
        "microsoft",
        "0x07",
        "exFAT",
        PartitionTypeInfoFlags::None,
        "exfat",
    ),
];

pub const PARTITION_TYPES: [PartitionTypeInfo; 37] = [
    PartitionTypeInfo::new(
        "dos",
        "generic",
        "0x05",
        "Extended",
        PartitionTypeInfoFlags::CreateOnly,
        "",
    ),
    PartitionTypeInfo::new(
        "dos",
        "generic",
        "0xee",
        "EFI GPT",
        PartitionTypeInfoFlags::System,
        "",
    ),
    PartitionTypeInfo::new(
        "dos",
        "generic",
        "0xef",
        "EFI (FAT-12/16/32)",
        PartitionTypeInfoFlags::System,
        "",
    ),
    PartitionTypeInfo::new(
        "dos",
        "linux",
        "0x82",
        "Linux swap",
        PartitionTypeInfoFlags::Swap,
        "",
    ),
    PartitionTypeInfo::new(
        "dos",
        "linux",
        "0x83",
        "Linux",
        PartitionTypeInfoFlags::None,
        "",
    ),
    PartitionTypeInfo::new(
        "dos",
        "linux",
        "0x85",
        "Linux Extended",
        PartitionTypeInfoFlags::CreateOnly,
        "",
    ),
    PartitionTypeInfo::new(
        "dos",
        "linux",
        "0x8e",
        "Linux LVM",
        PartitionTypeInfoFlags::Raid,
        "",
    ),
    PartitionTypeInfo::new(
        "dos",
        "linux",
        "0xfd",
        "Linux RAID auto",
        PartitionTypeInfoFlags::Raid,
        "",
    ),
    PartitionTypeInfo::new(
        "dos",
        "microsoft",
        "0x01",
        "FAT12",
        PartitionTypeInfoFlags::None,
        "",
    ),
    PartitionTypeInfo::new(
        "dos",
        "microsoft",
        "0x04",
        "FAT16 <32M",
        PartitionTypeInfoFlags::None,
        "",
    ),
    PartitionTypeInfo::new(
        "dos",
        "microsoft",
        "0x06",
        "FAT16",
        PartitionTypeInfoFlags::None,
        "",
    ),
    PartitionTypeInfo::new(
        "dos",
        "microsoft",
        "0x07",
        "NTFS/exFAT/HPFS",
        PartitionTypeInfoFlags::None,
        "",
    ),
    PartitionTypeInfo::new(
        "dos",
        "microsoft",
        "0x0b",
        "W95 FAT32",
        PartitionTypeInfoFlags::None,
        "",
    ),
    PartitionTypeInfo::new(
        "dos",
        "microsoft",
        "0x0c",
        "W95 FAT32 (LBA)",
        PartitionTypeInfoFlags::None,
        "",
    ),
    PartitionTypeInfo::new(
        "dos",
        "microsoft",
        "0x0e",
        "W95 FAT16 (LBA)",
        PartitionTypeInfoFlags::None,
        "",
    ),
    PartitionTypeInfo::new(
        "dos",
        "microsoft",
        "0x0f",
        "W95 Ext d (LBA)",
        PartitionTypeInfoFlags::CreateOnly,
        "",
    ),
    PartitionTypeInfo::new(
        "dos",
        "microsoft",
        "0x11",
        "Hidden FAT12",
        PartitionTypeInfoFlags::Hidden,
        "",
    ),
    PartitionTypeInfo::new(
        "dos",
        "microsoft",
        "0x14",
        "Hidden FAT16 <32M",
        PartitionTypeInfoFlags::Hidden,
        "",
    ),
    PartitionTypeInfo::new(
        "dos",
        "microsoft",
        "0x16",
        "Hidden FAT16",
        PartitionTypeInfoFlags::Hidden,
        "",
    ),
    PartitionTypeInfo::new(
        "dos",
        "microsoft",
        "0x17",
        "Hidden HPFS/NTFS",
        PartitionTypeInfoFlags::Hidden,
        "",
    ),
    PartitionTypeInfo::new(
        "dos",
        "microsoft",
        "0x1b",
        "Hidden W95 FAT32",
        PartitionTypeInfoFlags::Hidden,
        "",
    ),
    PartitionTypeInfo::new(
        "dos",
        "microsoft",
        "0x1c",
        "Hidden W95 FAT32 (LBA)",
        PartitionTypeInfoFlags::Hidden,
        "",
    ),
    PartitionTypeInfo::new(
        "dos",
        "microsoft",
        "0x1e",
        "Hidden W95 FAT16 (LBA)",
        PartitionTypeInfoFlags::Hidden,
        "",
    ),
    PartitionTypeInfo::new(
        "dos",
        "other",
        "0x10",
        "OPUS",
        PartitionTypeInfoFlags::None,
        "",
    ),
    PartitionTypeInfo::new(
        "dos",
        "other",
        "0x12",
        "Compaq diagnostics",
        PartitionTypeInfoFlags::None,
        "",
    ),
    PartitionTypeInfo::new(
        "dos",
        "other",
        "0x3c",
        "PartitionMagic",
        PartitionTypeInfoFlags::None,
        "",
    ),
    PartitionTypeInfo::new(
        "dos",
        "other",
        "0x81",
        "Minix",
        PartitionTypeInfoFlags::None,
        "",
    ),
    PartitionTypeInfo::new(
        "dos",
        "other",
        "0x84",
        "Hibernation",
        PartitionTypeInfoFlags::None,
        "",
    ),
    PartitionTypeInfo::new(
        "dos",
        "other",
        "0xa0",
        "Hibernation",
        PartitionTypeInfoFlags::None,
        "",
    ),
    PartitionTypeInfo::new(
        "dos",
        "other",
        "0xa5",
        "FreeBSD",
        PartitionTypeInfoFlags::None,
        "",
    ),
    PartitionTypeInfo::new(
        "dos",
        "other",
        "0xa6",
        "OpenBSD",
        PartitionTypeInfoFlags::None,
        "",
    ),
    PartitionTypeInfo::new(
        "dos",
        "other",
        "0xa8",
        "Mac OS X",
        PartitionTypeInfoFlags::None,
        "",
    ),
    PartitionTypeInfo::new(
        "dos",
        "other",
        "0xaf",
        "Mac OS X",
        PartitionTypeInfoFlags::None,
        "",
    ),
    PartitionTypeInfo::new(
        "dos",
        "other",
        "0xbe",
        "Solaris boot",
        PartitionTypeInfoFlags::None,
        "",
    ),
    PartitionTypeInfo::new(
        "dos",
        "other",
        "0xbf",
        "Solaris",
        PartitionTypeInfoFlags::None,
        "",
    ),
    PartitionTypeInfo::new(
        "dos",
        "other",
        "0xeb",
        "BeOS BFS",
        PartitionTypeInfoFlags::None,
        "",
    ),
    PartitionTypeInfo::new(
        "dos",
        "other",
        "0xec",
        "SkyOS SkyFS",
        PartitionTypeInfoFlags::None,
        "",
    ),
];
