FROM ubuntu:24.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    ca-certificates \
    curl \
    cargo \
    rustc \
    dbus \
    policykit-1 \
    lvm2 \
    mdadm \
    btrfs-progs \
    util-linux \
    parted \
    mount \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
COPY storage-testing/container/run-harness.sh /usr/local/bin/run-harness.sh
COPY resources/systemd/org.cosmic.ext.Storage.Service.conf /usr/share/dbus-1/system.d/org.cosmic.ext.Storage.Service.conf
COPY resources/systemd/org.cosmic.ext.storage.service.policy /usr/share/polkit-1/actions/org.cosmic.ext.storage.service.policy
RUN chmod +x /usr/local/bin/run-harness.sh
ENTRYPOINT ["/usr/local/bin/run-harness.sh"]
